### ISSUE TITLE
Relative path to website is bad idea

### ISSUE THREAD

**Issue by FaustinCarter** [adamanderson/he10_fridge_control#1]
Should change the relative path to the website directory to some kind of smarter path so that the logger can be run from any location.

**Comment by adamanderson** [comment]
I'm not sure I agree. If you have your web server operating in the canonical Linux location, you can just symlink all the web files inside the repo to that location. This keeps the repository structure intact, keeping the website files under version control. The same argument applies for moving the logger script. Moving it outside the repository breaks version control, which should not be supported unless there is a very good reason to do so. But do let me know if I'm misunderstanding your argument here. If the symlink trick wasn't obvious, then I'm quite happy to add info about that to the docs.

**Comment by FaustinCarter** [comment]
Right. I think we agree. I'm just saying that the "relative" part of the path should be referenced to wherever the fridge logger file lives, not referenced to wherever the fridge logger is called from. For instance, the following does not generate an error:

```
cd path_where_fridge_logger_lives
python fridge_logger.py
```
Whereas this does generate an error, and I think it shouldn't:

```
python path_where_fridge_logger_lives/fridge_logger.py
```

**Comment by adamanderson** [comment]
Ah, got it. I had misunderstood your point. Yes, I will certainly change that.

**Comment by FaustinCarter** [comment]
I have added a branch called fix_paths. I have also fixed it. You should test it on your end. If there aren't any problems, we can merge it in.

**Comment by adamanderson** [comment]
Tested and merged.
